version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/docker-tutorial
      - /docker-tutorial/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=test
      - MONGO_PASSWORD=mypw
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=mypw
