version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/docker-tutorial
      - /docker-tutorial/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
